# Generated by Django 3.2.5 on 2022-09-12 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('link', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='images/portfolio/')),
                ('gallery_image_one', models.ImageField(blank=True, upload_to='images/portfolio/')),
                ('gallery_image_two', models.ImageField(blank=True, upload_to='images/portfolio/')),
                ('is_available', models.BooleanField(default=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
