# Generated by Django 3.2.5 on 2022-09-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
