# Generated by Django 3.2.5 on 2022-09-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myGithubApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GithubItems',
            new_name='GithubItem',
        ),
    ]
