# Generated by Django 3.2.5 on 2022-09-12 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myGithubApp', '0002_rename_githubitems_githubitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubitem',
            old_name='repo_image',
            new_name='repository_image_one',
        ),
        migrations.AddField(
            model_name='githubitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='githubitem',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='githubitem',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='githubitem',
            name='repository_image_two',
            field=models.ImageField(blank=True, upload_to='images/repositories/'),
        ),
        migrations.AddField(
            model_name='githubitem',
            name='repository_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubitem',
            name='repository_thumbnail',
            field=models.ImageField(blank=True, upload_to='images/repositories/'),
        ),
        migrations.AlterField(
            model_name='githubitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='githubitem',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
